# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    before: cargo install tauri-cli # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    init: cargo tauri build # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: cargo tauri dev

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
